#名称
name: 发布到maven中央仓库
#触发器
on:
  workflow_dispatch:
#任务
jobs:
  publish:
    #任务环境
    runs-on: ubuntu-latest
    #步骤
    steps:
      #检查最新代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #设置java环境
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      #给gradle脚本运行权限
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      #发布到maven
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}